fail_fast: true

exclude: |
  (?x)^(
      notebooks/process_sandbox\.ipynb|
      src/cerf/data_acquisition_scrape\.py|
      src/disaster_charter/data_acquisition_scrape\.py|
      src/glide/data_acquisition_scrape\.py|
      docs/NOTEBOOK_DATASETS\.md
  )$

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.23
    hooks:
      - id: pymarkdown
        exclude: docs/DATASETS.md
  - repo: local
    hooks:
      - id: nbqa-ruff
        name: nbqa-ruff
        entry: poetry run nbqa ruff
        language: system
        files: \.ipynb$
      - id: nbqa-ruff-format
        name: nbqa-ruff-format
        entry: poetry run nbqa ruff --fix
        language: system
        files: \.ipynb$
